#CID-2152:Ensure the Permissions set for the '/etc/passwd' file is set to "644"

- name: Ensure permissions for /etc/passwd are set to 644
  hosts: all
  become: true
  tasks:
    - name: Set permissions for /etc/passwd to 644
      file:
        path: /etc/passwd
        mode: '0644'

#CID-2240:Ensure sshd PermitEmptyPasswords is disabled

- name: Ensure sshd PermitEmptyPasswords is disabled
  hosts: all
  become: true
  tasks:
    - name: Set PermitEmptyPasswords to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
        state: present
        
#CID-7948:Ensure the telnet client is not installed

- name: Remove telnet client
  hosts: all
  become: true
  tasks:
    - name: Remove telnet package
      package:
        name: telnet
        state: absent


#CID-14606:Ensure 'nosuid' option is set on '/home' partition

- name: Ensure 'nosuid' option is set on '/home' partition
  hosts: all
  become: true
  tasks:
    - name: Ensure 'nosuid' is set for /home in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*\s+/home\s+.*\s+)(\S.*)$'
        line: '\1\2,nosuid'
        backrefs: yes
      notify:
        - Remount /home
  handlers:
    - name: Remount /home
      command: mount -o remount /home

#CID-2234:Ensure SSH MaxAuthTries is set to 4 or less

- name: Configure SSH max authentication attempts
  hosts: all
  become: true
  tasks:
    - name: Set MaxAuthTries to 4
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries'
        line: 'MaxAuthTries 4'
        state: present

#CID-16048:Ensure ufw package is installed

- name: Ensure ufw package is installed
  hosts: all
  become: true
  tasks:
    - name: Install ufw package
      package:
        name: ufw
        state: present

 #CID-16066:Ensure audit log directory permissions are set to 750

- name: Ensure ufw is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable ufw
      command: ufw --force enable
      register: ufw_enable
      changed_when: "'Firewall is active and enabled' in ufw_enable.stdout"

 #CID-24932:Ensure the permissions of '*.conf'  and '*.rules' files under '/etc/audit/' directory is set to "640" with root ownership

- name: Ensure permissions and ownership of audit config and rules files
  hosts: all
  become: true
  tasks:
    - name: Set permissions and ownership for *.conf files
      file:
        path: "{{ item }}"
        mode: '0640'
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.conf

    - name: Set permissions and ownership for *.rules files
      file:
        path: "{{ item }}"
        mode: '0640'
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.rules
 
 #CID-24933:Ensure the ownership of '*.conf' and '*.rules' files under '/etc/audit/' directory is set to "root"
 
- name: Ensure ownership of audit configuration and rules files
  hosts: all
  become: true
  tasks:
    - name: Set ownership for *.conf files
      file:
        path: "{{ item }}"
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.conf

    - name: Set ownership for *.rules files
      file:
        path: "{{ item }}"
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.rules
        
#CID-23747: Ensure 'systemd-journald.service' service is enabled

- name: Ensure systemd-journald.service is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable systemd-journald.service
      systemd:
        name: systemd-journald.service
        enabled: yes

#CID-9335: Ensure the rsyslog service is enabled

- name: Ensure rsyslog service is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable rsyslog service
      systemd:
        name: rsyslog
        enabled: yes

#CID-17570: Ensure the logging messages for '*.*'(all facilities) in the '/etc/rsyslog.d/*' files is enabled
---
- name: Ensure logging for all facilities is enabled in /etc/rsyslog.d/*
  hosts: all
  become: true
  tasks:
    - name: Ensure *.* logging is configured in /etc/rsyslog.d/
      blockinfile:
        path: "/etc/rsyslog.d/99-all-facilities.conf"
        create: yes
        block: |
          # Log all facilities and all severities
          *.* /var/log/all.log
      notify:
        - Restart rsyslog

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted

#CID-10666: Ensure the '$FileCreateMode' setting within '/etc/rsyslog.conf' file is configured

- name: Ensure $FileCreateMode is configured in /etc/rsyslog.conf
  hosts: all
  become: true
  tasks:
    - name: Set $FileCreateMode in /etc/rsyslog.conf
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^\$FileCreateMode'
        line: '$FileCreateMode 0640'
        state: present
        insertafter: '^#.*Global Directives'
      notify:
        - Restart rsyslog

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
        
#CID-19583: Ensure 'FileCreateMode' defined within /etc/rsyslog.d/ files is configured

- name: Ensure $FileCreateMode is configured in /etc/rsyslog.conf
  hosts: all
  become: true
  tasks:
    - name: Set $FileCreateMode in /etc/rsyslog.conf
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^\$FileCreateMode'
        line: '$FileCreateMode 0640'
        state: present
        insertafter: '^#.*Global Directives'
      notify:
        - Restart rsyslog

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted



