#CID-2152:Ensure the Permissions set for the '/etc/passwd' file is set to "644"

- name: Ensure permissions for /etc/passwd are set to 644
  hosts: all
  become: true
  tasks:
    - name: Set permissions for /etc/passwd to 644
      file:
        path: /etc/passwd
        mode: '0644'

#CID-2240:Ensure sshd PermitEmptyPasswords is disabled

- name: Ensure sshd PermitEmptyPasswords is disabled
  hosts: all
  become: true
  tasks:
    - name: Set PermitEmptyPasswords to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
        state: present
        
#CID-7948:Ensure the telnet client is not installed

- name: Remove telnet client
  hosts: all
  become: true
  tasks:
    - name: Remove telnet package
      package:
        name: telnet
        state: absent


#CID-14606:Ensure 'nosuid' option is set on '/home' partition

- name: Ensure 'nosuid' option is set on '/home' partition
  hosts: all
  become: true
  tasks:
    - name: Ensure 'nosuid' is set for /home in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*\s+/home\s+.*\s+)(\S.*)$'
        line: '\1\2,nosuid'
        backrefs: yes
      notify:
        - Remount /home
  handlers:
    - name: Remount /home
      command: mount -o remount /home

#CID-2234:Ensure SSH MaxAuthTries is set to 4 or less

- name: Configure SSH max authentication attempts
  hosts: all
  become: true
  tasks:
    - name: Set MaxAuthTries to 4
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries'
        line: 'MaxAuthTries 4'
        state: present

#CID-16048:Ensure ufw package is installed

- name: Ensure ufw package is installed
  hosts: all
  become: true
  tasks:
    - name: Install ufw package
      package:
        name: ufw
        state: present

 #CID-16066:Ensure audit log directory permissions are set to 750

- name: Ensure ufw is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable ufw
      command: ufw --force enable
      register: ufw_enable
      changed_when: "'Firewall is active and enabled' in ufw_enable.stdout"

 #CID-24932:Ensure the permissions of '*.conf'  and '*.rules' files under '/etc/audit/' directory is set to "640" with root ownership

- name: Ensure permissions and ownership of audit config and rules files
  hosts: all
  become: true
  tasks:
    - name: Set permissions and ownership for *.conf files
      file:
        path: "{{ item }}"
        mode: '0640'
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.conf

    - name: Set permissions and ownership for *.rules files
      file:
        path: "{{ item }}"
        mode: '0640'
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.rules
 


