
- name: Ensure $FileCreateMode is configured in /etc/rsyslog.conf
  hosts: all
  become: true
  tasks:
    - name: Set $FileCreateMode in /etc/rsyslog.conf
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^\$FileCreateMode'
        line: '$FileCreateMode 0640'
        state: present
        insertafter: '^#.*Global Directives'
      notify:
        - Restart rsyslog

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
