---
- name: Ensure permissions and ownership for /sbin/auditctl
  hosts: all
  become: true
  tasks:
    - name: Set permissions and ownership for /sbin/auditctl
      file:
        path: /sbin/auditctl
        mode: '0755'
        owner: root
        group: root
