
- name: Ensure ownership of audit configuration and rules files
  hosts: all
  become: true
  tasks:
    - name: Set ownership for *.conf files
      file:
        path: "{{ item }}"
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.conf

    - name: Set ownership for *.rules files
      file:
        path: "{{ item }}"
        owner: root
        group: root
      with_fileglob:
        - /etc/audit/*.rules
