
- name: Ensure systemd-journald.service is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable systemd-journald.service
      systemd:
        name: systemd-journald.service
        enabled: yes
