#CID-16066:Ensure the Permission of the audit log directory on host is set to "750"
 
- name: Ensure ufw is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable ufw
      command: ufw --force enable
      register: ufw_enable
      changed_when: "'Firewall is active and enabled' in ufw_enable.stdout"
