#CID-2152:Ensure the Permissions set for the '/etc/passwd' file is set to "644"

- name: Ensure permissions for /etc/passwd are set to 644
  hosts: all
  become: true
  tasks:
    - name: Set permissions for /etc/passwd to 644
      file:
        path: /etc/passwd
        mode: '0644'
