
- name: Ensure permissions and ownership of /sbin/auditd
  hosts: all
  become: true
  tasks:
    - name: Set permissions and ownership for /sbin/auditd
      file:
        path: /sbin/auditd
        mode: '0755'
        owner: root
        group: root
