#CID-16049:Ensure the ufw(Uncomplicated Firewall) on the system is enabled
 
- name: Ensure ufw is enabled
  hosts: all
  become: true
  tasks:
    - name: Enable ufw
      command: ufw --force enable
      register: ufw_enable
      changed_when: "'Firewall is active and enabled' in ufw_enable.stdout"
