#CID-16066:Ensure the Permission of the audit log directory on host is set to "750"
---
- name: Ensure audit log directory permissions are set to 750
  hosts: all
  become: true
  tasks:
    - name: Set permissions on audit log directory
      file:
        path: /var/log/audit
        mode: '0750'
        state: directory
